#  This workflow will build a Java project with Maven
#  For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Push to Docker Hub

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: gersho23/my-projects
          tags: myname
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
     
