#  This workflow will build a Java project with Maven
#  For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
  
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-18.04, windows-latest]

    steps:
      - name: Step 1
        uses: actions/checkout@v2
      
      - name: Step 2 - Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Step three - Build with Maven
        run: mvn -B package --file pom.xml

      - name: Step four
        run: dir
        
         
      - name: Step six - Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: gersho23/my-projects
          tags: myname
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
